-- Personal finance ledger: accounts, categories, transactions, budgets, net
-- worth snapshots, recurring bills and an ingestion audit log. DDL follows
-- 0007_notifications.sql: uuid/identity PKs, timestamptz, jsonb default '{}',
-- `create ... if not exists`, partial unique indexes instead of nullable
-- UNIQUE constraints, no RLS.
--
-- Category taxonomy and budgeting rule (50/30/20, bucketed as
-- necesidad/deseo/ahorro_inversion) are taken from the user's own study notes
-- on the "Money Coach" book (Obsidian vault, analyzed 2026-09-16), not
-- invented generically -- see Presupuesto.pdf / Capitulo 2 for the source.
--
-- MONEY IS NEVER `numeric` HERE. Every monetary column is `bigint` holding
-- CENTS. Reason: collector/local_repository.py registers a global
-- `numeric` -> FloatLoader adapter so pandas DataFrames keep float dtypes for
-- OHLCV math. That adapter is correct for prices and corrosive for a ledger --
-- binary floats cannot represent 0.10 exactly, so sums drift by cents over
-- thousands of rows. Integer cents sidestep the adapter entirely and make every
-- total exact by construction.
--
-- SIGN CONVENTION: `amount_cents` is ALWAYS positive. The `kind` column carries
-- the direction. A signed amount plus a kind column is two sources of truth for
-- the same fact, and they drift.

-- -- Accounts -----------------------------------------------------------------
-- Where money physically sits. Kept separate from categories so "paid the rent
-- with the credit card" records both the purpose and the funding source.

create table if not exists finance_accounts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  account_type text not null,              -- 'cash' | 'debit' | 'credit' | 'savings' | 'investment'
  currency char(3) not null default 'USD',
  opening_balance_cents bigint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Partial + lower(): only ACTIVE accounts must have unique names, so a retired
-- "Efectivo" never blocks creating a fresh one years later.
create unique index if not exists finance_accounts_active_name_key
  on finance_accounts(lower(name)) where is_active;

-- -- Categories ---------------------------------------------------------------
-- Hierarchical via parent_id. `slug` is the STABLE key the Telegram bot matches
-- free text against ("120 comida almuerzo" -> slug 'alimentacion'), so
-- renaming the display name never breaks capture.
--
-- `budget_bucket` implements the book's 50/30/20 rule: every expense category
-- is either a Necesidad (50%), a Deseo (30%) or Ahorro e Inversion (20%).
-- Null for income/transfer categories, which aren't allocated, they ARE the
-- income being allocated.

create table if not exists finance_categories (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references finance_categories(id) on delete restrict,
  slug text not null,
  name text not null,
  kind text not null,                      -- 'expense' | 'income' | 'transfer'
  budget_bucket text
    constraint finance_categories_budget_bucket_check
    check (budget_bucket is null or budget_bucket in ('necesidad', 'deseo', 'ahorro_inversion')),
  emoji text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists finance_categories_slug_key
  on finance_categories(slug);
create index if not exists finance_categories_kind_idx
  on finance_categories(kind) where is_active;

-- -- Transactions -------------------------------------------------------------
-- The ledger. Every other table exists to give these rows meaning.

create table if not exists finance_transactions (
  id uuid primary key default gen_random_uuid(),

  -- THE SYNC CONTRACT. Generated by the capture surface (Telegram adapter, UI,
  -- importer) BEFORE the row ever reaches Postgres, which makes ingestion
  -- idempotent: replaying a batch upserts instead of duplicating. This single
  -- column is what keeps the capture surface swappable -- a future Capacitor
  -- APK produces the same contract and the backend never learns it changed.
  client_id uuid not null,

  account_id uuid not null references finance_accounts(id) on delete restrict,
  category_id uuid references finance_categories(id) on delete set null,
  kind text not null,                      -- 'expense' | 'income' | 'transfer'

  amount_cents bigint not null check (amount_cents >= 0),
  currency char(3) not null,

  -- Multi-currency from day one: spending happens in local currency while the
  -- investment engine prices in USD, so the "what can I invest" bridge needs a
  -- rate. A ratio, NOT a ledger value -- only *_cents columns are authoritative
  -- money. Null when currency already equals the base currency.
  fx_rate_to_base numeric(18,8),
  -- Materialized so monthly aggregation never joins a rate table. Trade-off
  -- accepted: correcting a historical rate requires recomputing this column.
  amount_base_cents bigint,

  occurred_at timestamptz not null,        -- when the money actually moved
  recorded_at timestamptz not null default now(),  -- when it reached this database

  merchant text,
  notes text,
  source text not null default 'telegram', -- 'telegram' | 'ui' | 'import'
  raw_input text,                          -- literal captured message, for audit and re-parsing
  payload jsonb not null default '{}'::jsonb,

  -- Tombstone, not a hard delete: a row deleted on the phone while offline must
  -- still be able to travel to the database and win. A physical DELETE cannot
  -- be synced -- the absence of a row is indistinguishable from a row that never
  -- arrived.
  deleted_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Idempotency key. NOT partial: a deleted transaction still occupies its
-- client_id, so a replayed batch resurrects nothing.
create unique index if not exists finance_transactions_client_id_key
  on finance_transactions(client_id);

-- Exact shape of the three reads that matter: the ledger feed, per-category
-- month rollups, and per-account balances. Partial on live rows because every
-- analytical query filters tombstones out.
create index if not exists finance_transactions_occurred_idx
  on finance_transactions(occurred_at desc) where deleted_at is null;
create index if not exists finance_transactions_category_idx
  on finance_transactions(category_id, occurred_at desc) where deleted_at is null;
create index if not exists finance_transactions_account_idx
  on finance_transactions(account_id, occurred_at desc) where deleted_at is null;

-- -- Budgets ------------------------------------------------------------------
-- `period_month` null = the standing monthly budget; a dated row (always day 1)
-- overrides it for that month. Two partial indexes rather than
-- `unique (category_id, period_month)` for the reason spelled out in 0007:
-- Postgres treats NULLs as distinct, so two standing budgets would both pass.
--
-- `percent_of_income` is optional companion metadata: the book budgets in
-- percent of income first (the 50/30/20 sliders), then translates that into a
-- peso ceiling. `limit_cents` stays the one number every other query reads;
-- `percent_of_income` is just where that number came from.

create table if not exists finance_budgets (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references finance_categories(id) on delete cascade,
  period_month date,
  limit_cents bigint not null check (limit_cents >= 0),
  percent_of_income numeric(5,2)
    check (percent_of_income is null or (percent_of_income >= 0 and percent_of_income <= 100)),
  currency char(3) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists finance_budgets_period_key
  on finance_budgets(category_id, period_month) where period_month is not null;
create unique index if not exists finance_budgets_standing_key
  on finance_budgets(category_id) where period_month is null;

-- -- Net worth ------------------------------------------------------------
-- Dated snapshots of assets vs. liabilities (the book's "Patrimonio"
-- worksheet). Formula: patrimonio = sum(assets) - sum(liabilities).
--
-- Totals are deliberately NOT stored on the snapshot row. A cached total next
-- to its own line items is the same two-sources-of-truth problem the
-- transactions table's sign convention comment already warns against --
-- compute it at read time from finance_net_worth_items instead.

create table if not exists finance_net_worth_snapshots (
  id uuid primary key default gen_random_uuid(),
  snapshot_date date not null,
  notes text,
  created_at timestamptz not null default now()
);

-- One snapshot per date: prevents an accidental double entry on the same day,
-- without forcing a fixed cadence (the book recommends monthly, not daily).
create unique index if not exists finance_net_worth_snapshots_date_key
  on finance_net_worth_snapshots(snapshot_date);
create index if not exists finance_net_worth_snapshots_date_idx
  on finance_net_worth_snapshots(snapshot_date desc);

create table if not exists finance_net_worth_items (
  id uuid primary key default gen_random_uuid(),
  snapshot_id uuid not null references finance_net_worth_snapshots(id) on delete cascade,
  is_asset boolean not null,
  label text not null,
  -- Soft classification, not a fixed enum: the worksheet itself leaves this
  -- freeform. Illustrative values from the book: cash, fixed_income (CETES),
  -- equities, real_estate, retirement (AFORE/PPR) on the asset side;
  -- credit_card, personal_loan, auto_loan, mortgage on the liability side.
  item_type text not null default 'other',
  amount_cents bigint not null check (amount_cents >= 0),
  currency char(3) not null,
  fx_rate_to_base numeric(18,8),
  amount_base_cents bigint,
  created_at timestamptz not null default now()
);

create index if not exists finance_net_worth_items_snapshot_idx
  on finance_net_worth_items(snapshot_id);

-- -- Recurring bills --------------------------------------------------------
-- The book's "Calendario de Pagos": a due-date tracker, distinct from the
-- budget categories above. `anchor_due_date` + `frequency` compute every
-- future occurrence in application code rather than storing a fixed
-- day-of-month, which would break on months that don't have that day (a
-- bill anchored on the 31st has no 31st to fall on in April).

create table if not exists finance_recurring_bills (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category_id uuid references finance_categories(id) on delete set null,
  account_id uuid references finance_accounts(id) on delete set null,
  amount_cents bigint not null check (amount_cents >= 0),
  currency char(3) not null,
  frequency text not null
    check (frequency in ('weekly', 'biweekly', 'monthly', 'bimonthly', 'quarterly', 'semiannual', 'annual')),
  anchor_due_date date not null,
  reminder_days_before integer not null default 3 check (reminder_days_before >= 0),
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists finance_recurring_bills_active_idx
  on finance_recurring_bills(is_active) where is_active;

-- One row per occurrence: the digital equivalent of the worksheet's 12 monthly
-- checkboxes, generalized to any frequency. `transaction_id` links a paid
-- occurrence to the ledger row that recorded it, so "marked paid" and "logged
-- as an expense" stay one fact instead of two that can quietly disagree.

create table if not exists finance_recurring_bill_payments (
  id uuid primary key default gen_random_uuid(),
  bill_id uuid not null references finance_recurring_bills(id) on delete cascade,
  due_date date not null,
  transaction_id uuid references finance_transactions(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'paid', 'skipped')),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

-- One record per occurrence; the app is responsible for generating the next
-- pending row once the current one is settled.
create unique index if not exists finance_recurring_bill_payments_occurrence_key
  on finance_recurring_bill_payments(bill_id, due_date);
create index if not exists finance_recurring_bill_payments_bill_idx
  on finance_recurring_bill_payments(bill_id);
-- Exact shape of the reminder job's read: everything due soon that hasn't
-- been handled yet. This is what a future job wires into the EXISTING
-- ops/notification_rules.py + ops/telegram_notifier.py pipeline (0007) --
-- no new notification transport needed, just a new rule_type reading this.
create index if not exists finance_recurring_bill_payments_pending_idx
  on finance_recurring_bill_payments(due_date) where status = 'pending';

-- -- Ingestion audit ----------------------------------------------------------
-- One row per pull from a capture surface. `cursor_update_id` is Telegram's
-- getUpdates high-water mark: the audit log IS the cursor, so there is no
-- separate mutable state table to fall out of sync with reality. The next pull
-- reads max(cursor_update_id) over non-failed batches.

create table if not exists finance_sync_batches (
  id bigint primary key generated always as identity,
  source text not null,                    -- 'telegram' | 'ui' | 'import'
  cursor_update_id bigint,
  received_count integer not null default 0,
  applied_count integer not null default 0,
  rejected_count integer not null default 0,
  status text not null,                    -- 'ok' | 'partial' | 'failed'
  error_reason text,
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

-- Excluding 'failed' from the cursor index is the whole point: a crashed pull
-- must never advance the high-water mark, otherwise its unconsumed Telegram
-- updates are dropped forever.
create index if not exists finance_sync_batches_cursor_idx
  on finance_sync_batches(source, cursor_update_id desc) where status <> 'failed';
create index if not exists finance_sync_batches_recent_idx
  on finance_sync_batches(source, started_at desc);

-- -- Seed ---------------------------------------------------------------------
-- Accounts: a reasonable default set, editable later.

insert into finance_accounts (name, account_type, currency) values
  ('Efectivo',        'cash',    'USD'),
  ('Tarjeta debito',  'debit',   'USD'),
  ('Tarjeta credito', 'credit',  'USD'),
  ('Ahorro',          'savings', 'USD')
on conflict do nothing;

-- Categories: the book's exact 10-category budget worksheet (expense side),
-- each bucketed into the 50/30/20 rule, plus the book's named income sources.
-- Slugs are accent-free and lowercase so free-text matching from a phone
-- keyboard is forgiving.

insert into finance_categories (slug, name, kind, budget_bucket, emoji) values
  ('vivienda',           'Vivienda',              'expense', 'necesidad',       '🏠'),
  ('alimentacion',       'Alimentacion',          'expense', 'necesidad',       '🍽'),
  ('transporte',         'Transporte',            'expense', 'necesidad',       '🚗'),
  ('servicios',          'Servicios',             'expense', 'necesidad',       '💡'),
  ('salud',              'Salud',                 'expense', 'necesidad',       '🩺'),
  ('educacion-hijos',    'Educacion / Hijos',     'expense', 'necesidad',       '📚'),
  ('gastos-personales',  'Gastos Personales',     'expense', 'deseo',           '👛'),
  ('entretenimiento',    'Entretenimiento',       'expense', 'deseo',           '🎬'),
  ('ropa',               'Ropa',                  'expense', 'deseo',           '👕'),
  ('ahorro-inversion',   'Ahorro e Inversion',    'expense', 'ahorro_inversion','💰'),
  ('sueldo',             'Sueldo',                'income',  null,              '💼'),
  ('honorarios',         'Honorarios / Freelance','income',  null,              '💻'),
  ('rentas',             'Rentas',                'income',  null,              '🏘'),
  ('dividendos',         'Dividendos',            'income',  null,              '📊'),
  ('ganancias-inversion','Ganancias de inversion','income',  null,              '📈'),
  ('otros-ingresos',     'Otros ingresos',        'income',  null,              '➕')
on conflict do nothing;
